language: python

services:
  - docker

version:
  - "3.9"


install:
  - make deps

script:
  - make lint
  - make test
  - make docker_build
  - make docker_push

deploy:
  provider: heroku
  app: agile-spire-77773
  api_key: ${HEROKU_API_KEY}